import 'package:tech_linker_new/models/internship_model.dart';

   List<Internship> get jobsData => [
    Internship(
      id: '1',
      title: 'Customer Service Agent',
      company: 'TechSupport Solutions',
      location: 'USA',
      salary: '1200 Rs',
      timeAgo: '3 days ago',
      imageUrl: 'https://ui-avatars.com/api/?name=TechSupport&background=0066cc&color=fff',
      duration: '6 months',
      jobtime: 'Day Shift',
      jobtype: 'Remote',
    ),
    
    Internship(
      id: '2',
      title: 'Flutter Developer',
      company: 'Mobile Innovations',
      location: 'Pakistan',
      salary: '45,000 Rs',
      timeAgo: '1 day ago',
      imageUrl: 'https://ui-avatars.com/api/?name=Mobile+Innovations&background=42a5f5&color=fff',
      duration: 'Permanent',
      jobtime: 'Full Time',
      jobtype: 'On-site',
    ),
    
    Internship(
      id: '3',
      title: 'Digital Marketing Specialist',
      company: 'Growth Marketing Co.',
      location: 'Remote',
      salary: '25,000 Rs',
      timeAgo: '5 days ago',
      imageUrl: 'https://ui-avatars.com/api/?name=Growth+Marketing&background=66bb6a&color=fff',
      duration: '1 year',
      jobtime: 'Full Time',
      jobtype: 'Remote',
    ),
    
    Internship(
      id: '4',
      title: 'Data Entry Operator',
      company: 'DataPro Services',
      location: 'Lahore',
      salary: '18,000 Rs',
      timeAgo: '2 days ago',
      imageUrl: 'https://ui-avatars.com/api/?name=DataPro&background=ff7043&color=fff',
      duration: '3 months',
      jobtime: 'Part Time',
      jobtype: 'On-site',
    ),
    
    Internship(
      id: '5',
      title: 'Content Writer',
      company: 'Creative Words Agency',
      location: 'Karachi',
      salary: '30,000 Rs',
      timeAgo: '4 days ago',
      imageUrl: 'https://ui-avatars.com/api/?name=Creative+Words&background=ab47bc&color=fff',
      duration: 'Permanent',
      jobtime: 'Flexible',
      jobtype: 'Remote',
    ),
    
    Internship(
      id: '6',
      title: 'Virtual Assistant',
      company: 'VirtueAssist Global',
      location: 'Remote',
      salary: '22,000 Rs',
      timeAgo: '6 days ago',
      imageUrl: 'https://ui-avatars.com/api/?name=VirtueAssist&background=26c6da&color=fff',
      duration: '6 months',
      jobtime: 'Part Time',
      jobtype: 'Remote',
    ),
    
    Internship(
      id: '7',
      title: 'Graphic Designer',
      company: 'Design Studio Pro',
      location: 'Islamabad',
      salary: '35,000 Rs',
      timeAgo: '1 week ago',
      imageUrl: 'https://ui-avatars.com/api/?name=Design+Studio&background=ffa726&color=fff',
      duration: 'Permanent',
      jobtime: 'Full Time',
      jobtype: 'On-site',
    ),
    
    Internship(
      id: '8',
      title: 'Social Media Manager',
      company: 'SocialBuzz Marketing',
      location: 'Remote',
      salary: '28,000 Rs',
      timeAgo: '3 days ago',
      imageUrl: 'https://ui-avatars.com/api/?name=SocialBuzz&background=ec407a&color=fff',
      duration: '1 year',
      jobtime: 'Full Time',
      jobtype: 'Remote',
    ),
    
    Internship(
      id: '9',
      title: 'Web Developer',
      company: 'WebCraft Technologies',
      location: 'Faisalabad',
      salary: '50,000 Rs',
      timeAgo: '2 days ago',
      imageUrl: 'https://ui-avatars.com/api/?name=WebCraft&background=5c6bc0&color=fff',
      duration: 'Permanent',
      jobtime: 'Full Time',
      jobtype: 'Hybrid',
    ),
    
    Internship(
      id: '10',
      title: 'Online Tutor',
      company: 'EduTech Learning',
      location: 'Remote',
      salary: '20,000 Rs',
      timeAgo: '5 days ago',
      imageUrl: 'https://ui-avatars.com/api/?name=EduTech&background=66bb6a&color=fff',
      duration: '6 months',
      jobtime: 'Flexible',
      jobtype: 'Remote',
    ),
    
    Internship(
      id: '11',
      title: 'Sales Representative',
      company: 'SalesPro Solutions',
      location: 'Multan',
      salary: '25,000 Rs',
      timeAgo: '1 day ago',
      imageUrl: 'https://ui-avatars.com/api/?name=SalesPro&background=ff8a65&color=fff',
      duration: 'Permanent',
      jobtime: 'Full Time',
      jobtype: 'On-site',
    ),
    
    Internship(
      id: '12',
      title: 'UI/UX Designer',
      company: 'DesignFlow Studios',
      location: 'Remote',
      salary: '40,000 Rs',
      timeAgo: '4 days ago',
      imageUrl: 'https://ui-avatars.com/api/?name=DesignFlow&background=8e24aa&color=fff',
      duration: '1 year',
      jobtime: 'Full Time',
      jobtype: 'Remote',
    ),
    
    Internship(
      id: '13',
      title: 'Customer Support Chat Agent',
      company: 'ChatSupport 24/7',
      location: 'Remote',
      salary: '15,000 Rs',
      timeAgo: '2 days ago',
      imageUrl: 'https://ui-avatars.com/api/?name=ChatSupport&background=29b6f6&color=fff',
      duration: '3 months',
      jobtime: 'Night Shift',
      jobtype: 'Remote',
    ),
    
    Internship(
      id: '14',
      title: 'Video Editor',
      company: 'VideoMax Productions',
      location: 'Rawalpindi',
      salary: '32,000 Rs',
      timeAgo: '6 days ago',
      imageUrl: 'https://ui-avatars.com/api/?name=VideoMax&background=d32f2f&color=fff',
      duration: 'Permanent',
      jobtime: 'Full Time',
      jobtype: 'Hybrid',
    ),
    
    Internship(
      id: '15',
      title: 'SEO Specialist',
      company: 'SearchRank Agency',
      location: 'Remote',
      salary: '35,000 Rs',
      timeAgo: '1 week ago',
      imageUrl: 'https://ui-avatars.com/api/?name=SearchRank&background=388e3c&color=fff',
      duration: '1 year',
      jobtime: 'Full Time',
      jobtype: 'Remote',
    ),
  ];